---
id: "32dc9025-9050-46a1-a2db-f076ffbcd935"
name: "Bedroom: Default"
icon: mdi:home-lightbulb-outline
entities:
  switch.bedroom_lights_switch:
    state: "on"
  light.bedroom_lamp_light:
    state: "off"
