id: "25632083-d7d0-41f5-90de-0a26332c2bfa"
alias: "Bedroom: Bedtime"
tags:
  - bedroom
  - scenes
mode: queued
trace:
  stored_traces: 25

triggers:
  - id: to
    platform: state
    entity_id:
      - input_select.house_mode
    to: bedtime

variables:
  anchors:
    - &to_actions
      - alias: "Turn on bedtime scene"
        service: scene.turn_on
        target:
          entity_id: scene.bedroom_night
        data:
          transition: 2.5

action:
  - choose:
      - alias: "House mode changed to"
        conditions:
          - condition: trigger
            id: to
        sequence:
          <<: *to_actions
