id: "5ab5f017-59db-4c84-a097-0bfc848cee96"
alias: "Bedroom: Scene Button"
mode: queued
trace:
  stored_traces: 25

triggers:
  - id: "switch-on"
    platform: event
    event_type: zha_event
    event_data:
      device_id: 91cf3416653ada66678a711fa944bab6
      command: "on"

  - id: "switch-off"
    platform: event
    event_type: zha_event
    event_data:
      device_id: 91cf3416653ada66678a711fa944bab6
      command: "off"

variables:
  anchors:
    - &turn_off_lamp
      alias: "Turn off lamp"
      service: light.turn_off
      target:
        entity_id: light.bedroom_lamp_light

    - &turn_off_lights
      alias: "Turn off lights"
      service: switch.turn_off
      target:
        entity_id: switch.bedroom_lights_switch

    - &turn_on_sleep_mode
      alias: "Change house to sleep mode"
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "sleep"

    - &turn_on_lights
      alias: "Turn on light"
      service: switch.turn_on
      target:
        entity_id: switch.bedroom_lights_switch

    - &turn_on_lamp
      alias: "Turn on lamp"
      service: light.turn_on
      target:
        entity_id: light.bedroom_lamp_light

action:
  - choose:
      - alias: "Turn on when on button pressed"
        conditions:
          - condition: trigger
            id: switch-on
        sequence:
          - choose:
              conditions:
                or:
                  - alias: "House Mode - bedtime"
                    condition: state
                    entity_id: input_select.house_mode
                    state: "bedtime"
                  - alias: "House Mode - sleep"
                    condition: state
                    entity_id: input_select.house_mode
                    state: "sleep"
              sequence:
                - *turn_on_lamp
            default:
              - *turn_on_lights

      - alias: "Turn off when off button pressed"
        conditions:
          - condition: trigger
            id: switch-off
        sequence:
          - choose:
              conditions:
                - alias: "House Mode - bedtime"
                  condition: state
                  entity_id: input_select.house_mode
                  state: "bedtime"
              sequence:
                - *turn_off_lights
                - *turn_off_lamp
                - *turn_on_sleep_mode
            default:
              - *turn_off_lights
              - *turn_off_lamp
    default:
      - *turn_off_lights
      - *turn_off_lamp
