---
id: "5ab5f017-59db-4c84-a097-0bfc848cee96"
alias: "Bedroom: Scene Button"
mode: queued
trace:
  stored_traces: 25

triggers:
  - id: "switch-on"
    platform: event
    event_type: zha_event
    event_data:
      device_id: 91cf3416653ada66678a711fa944bab6
      command: "on"

  - id: "switch-off"
    platform: event
    event_type: zha_event
    event_data:
      device_id: 91cf3416653ada66678a711fa944bab6
      command: "off"

variables:
  # Map house modes to corresponding bedroom scenes
  scene_map:
    default: "scene.bedroom_default"
    wake_up: "scene.bedroom_default"
    work: "scene.bedroom_default"
    away: "scene.bedroom_away"
    dinner: "scene.bedroom_default"
    relaxation: "scene.bedroom_relaxation"
    bedtime: "scene.bedroom_bed_time"
    sleep: "scene.bedroom_sleep"

  house_mode: "{{ states('input_select.house_mode') }}"
  target_scene: "{{ scene_map.get(house_mode, 'scene.bedroom_default') }}"

action:
  - choose:
      - alias: "Turn on when on button pressed"
        conditions:
          - condition: trigger
            id: switch-on
        sequence:
          - alias: "Activate scene based on house mode"
            service: scene.turn_on
            target:
              entity_id: "{{ target_scene }}"

      - alias: "Turn off when off button pressed"
        conditions:
          - condition: trigger
            id: switch-off
        sequence:
          - choose:
              - alias: "Transition to sleep mode if in bedtime"
                conditions:
                  - condition: state
                    entity_id: input_select.house_mode
                    state: "bedtime"
                sequence:
                  - alias: "Change house to sleep mode"
                    service: input_select.select_option
                    target:
                      entity_id: input_select.house_mode
                    data:
                      option: "sleep"
                  - alias: "Activate sleep scene"
                    service: scene.turn_on
                    target:
                      entity_id: scene.bedroom_sleep
            default:
              - alias: "Turn off all bedroom lights"
                service: scene.turn_on
                target:
                  entity_id: scene.bedroom_sleep
