---
id: "1734868824566"
alias: "Living Room: Aircon"
description: >-
  Controls the aircon in the living room

  Turns it off every night at 2AM incase it was forgotten
trigger:
  - platform: time
    at: 02:00:00
condition: []
action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.living_room_aircon
    data:
      hvac_mode: "off"
mode: single
