id: '9e39e652-c9d4-4490-9382-b5e9eecbb06e'
alias: "Living Room: Camera"
description: >-
  Controls the living room camera on/off state

  Due to how the wyze cameras operates the power is turned on/off via. an http API.

  When the `input_boolean` for camera state is toggled this turns on/off the camera,
  it will then keep this `input_boolean` up to date if the sensor that checks the state
  from the wyze API updates.
mode: queued
trace:
  stored_traces: 25

triggers:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  - trigger: state
    entity_id: input_boolean.living_room_camera_state
    from: ~

  - trigger: state
    id: wyze-change
    entity_id: sensor.living_room_cam_power
    from: ~

variables:
  anchors:
    - &turn_on
      alias: "Turn on the camera"
      service: shell_command.turn_on_living_room_camera

    - &turn_off
      alias: "Turn off the camera"
      service: shell_command.turn_off_living_room_camera

    - &sync_on
      alias: Synchronize state to on
      sequence:
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.living_room_camera_state

    - &sync_off
      alias: Synchronize state to off
      sequence:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.living_room_camera_state

action:
  - choose:
    - alias: "Synchronize with wyze - on"
      conditions:
        - and:
          - condition: trigger
            id: "wyze-change"
          - condition: state
            state: "on"
            entity_id: "sensor.living_room_cam_power"

      sequence:
        - *sync_on

    - alias: "Synchronize with wyze - off"
      conditions:
        - and:
          - condition: trigger
            id: "wyze-change"
          - condition: state
            state: "off"
            entity_id: "sensor.living_room_cam_power"

      sequence:
        - *sync_off

    - alias: "Input boolean turned on"
      conditions:
        - condition: state
          entity_id: input_boolean.living_room_camera_state
          state: "on"

      sequence:
        - *turn_on

    - alias: "Input boolean turned off"
      conditions:
        - condition: state
          entity_id: input_boolean.living_room_camera_state
          state: "off"

      sequence:
        - *turn_off
