id: '9e39e652-c9d4-4490-9382-b5e9eecbb06e'
alias: "Living Room: Camera remote on"
triggers:
  - trigger: state
    entity_id: input_boolean.living_room_camera_state
    to: "on"
actions:
  - action: shell_command.turn_on_living_room_camera
