# NOTE: current limitation is that you can't turn off camera if house away is enabled
id: '9e39e652-c9d4-4490-9382-b5e9eecbb06e'
alias: "Living Room: Camera"
mode: queued
trace:
  stored_traces: 25

triggers:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  - trigger: state
    id: "turn-on"
    entity_id: input_boolean.living_room_camera_state
    to: "on"

  - trigger: state
    id: "turn-off"
    entity_id: input_boolean.living_room_camera_state
    to: "off"

  - platform: state
    id: "turn-on"
    entity_id:
      - input_boolean.house_mode_away
    to: "on"

  - platform: state
    id: "turn-off"
    entity_id:
      - input_boolean.house_mode_away
    to: "off"

  - platform: state
    id: "wyze-change"
    entity_id:
      - sensor.living_room_cam_power
    from: ~

variables:
  anchors:
    - &turn_on
      alias: "Turn on the camera"
      service: shell_command.turn_on_living_room_camera

    - &turn_off
      alias: "Turn off the camera"
      service: shell_command.turn_off_living_room_camera

    - &sync_on
      alias: Synchronize state to on
      sequence:
        - service: automation.turn_off
          target:
            entity_id: automation.living_room_camera_remote_on
        - service: input_boolean.turn_on
          target:
            entity_id: input_boolean.living_room_camera_state
        - service: automation.turn_on
          target:
            entity_id: automation.living_room_camera_remote_on

    - &sync_off
      alias: Synchronize state to off
      sequence:
        - service: automation.turn_off
          target:
            entity_id: automation.living_room_camera_remote_on
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.living_room_camera_state
        - service: automation.turn_on
          target:
            entity_id: automation.living_room_camera_remote_on


action:
  - choose:
    - alias: "Turn on when away mode activated or turned on"
      conditions:
        - or:
          - condition: trigger
            id: "turn-on"

      sequence:
        - *turn_on

    - alias: "Turn off when away mode de-activated or turned off"
      conditions:
        - or:
          - condition: trigger
            id: "turn-off"

      sequence:
        - *turn_off

    - alias: "Synchronize with house mode - turn on"
      conditions:
        - condition: state
          entity_id: input_boolean.house_mode_away
          state: "on"

      sequence:
        - *turn_on

    - alias: "Synchronize with house mode - turn off"
      conditions:
        - condition: state
          entity_id: input_boolean.house_mode_away
          state: "off"

      sequence:
        - *turn_off

    - alias: "Synchronize with wyze"
      conditions:
        - condition: trigger
          id: "wyze-change"

      sequence:
        - "*turn_{{ sensor.living_room_cam_power }}"
