# NOTE: current limitation is that you can't turn off camera if house away is enabled
#
id: '9e39e652-c9d4-4490-9382-b5e9eecbb06e'
alias: "Living Room Camera"
mode: queued
trace:
  stored_traces: 25

triggers:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  - trigger: state
    id: "turn-on"
    entity_id: input_boolean.living_room_camera_state
    to: "on"

  - trigger: state
    id: "turn-off"
    entity_id: input_boolean.living_room_camera_state
    to: "off"

  - platform: state
    id: "turn-on"
    entity_id:
      - input_boolean.house_mode_away
    to: "on"

  - platform: state
    id: "turn-off"
    entity_id:
      - input_boolean.house_mode_away
    to: "off"

variables:
  anchors:
    # TODO: Sync state step on 30s delay after action?
    - &turn_on
      alias: "Turn on the camera"
      service: shell_command.turn_on_living_room_camera

    - &turn_off
      alias: "Turn off the camera"
      service: shell_command.turn_off_living_room_camera

    - &sync_state
      alias: "Sync with Wyze state"
      sequence:
        - service: shell_command.get_living_room_camera_power_status
          response_variable: result
        - data:
            title: DEBUG
            message: {{ result.value }}
          action: notify.mobile_app_sam_phone

action:
  - choose:
    - alias: "Turn on when away mode activated or turned on"
      conditions:
        - or:
          - condition: trigger
            id: "turn-on"

      sequence:
        - *turn_on

    - alias: "Turn off when away mode de-activated or turned off"
      conditions:
        - or:
          - condition: trigger
            id: "turn-off"

      sequence:
        - *turn_off

    default:
      - *sync_state
