id: "94bea6be-6520-4227-b451-fee4d95df21f"
alias: "House: Away"
description: >-
  This is pretty much only required to turn off the input_boolean for living room camera state
  due to how this operates.

  Now also using to turn off lights etc. when leaving the house
mode: queued
trace:
  stored_traces: 25

triggers:
  - id: to_away
    platform: state
    entity_id:
      - input_select.house_mode
    to: away

  - id: from_away
    platform: state
    entity_id:
      - input_select.house_mode
    from: away

variables:
  anchors:
    - &to_away
      - alias: "Turn on All Away scenes"
        service: script.turn_on
        target:
          entity_id: script.away_scenes

    # This could potentially be changed to a script in the future
    - &from_away
      - alias: "Turn off the camera power input boolean"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.living_room_camera_state

action:
  - choose:
      - alias: "House mode changed to away"
        conditions:
          - condition: trigger
            id: to_away
        sequence:
          <<: *to_away

      - alias: "House mode changed from away"
        conditions:
          - condition: trigger
            id: from_away
        sequence:
          <<: *from_away
