id: '94bea6be-6520-4227-b451-fee4d95df21f'
alias: "House: Away"
description: >-
  This is pretty much only required to turn off the input_boolean for living room camera state
  due to how this operates
mode: queued
trace:
  stored_traces: 25

triggers:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  - platform: state
    entity_id:
      - input_boolean.house_mode_away
    from: ~


variables:
  anchors:
    - &turned_on
      alias: "Turn on the camera power input boolean"
      service: input_boolean.turn_on
      target:
        entity_id: input_boolean.living_room_camera_state

    - &turned_off
      alias: "Turn off the camera power input boolean"
      service: input_boolean.turn_off
      target:
        entity_id: input_boolean.living_room_camera_state

action:
  - choose:
    - alias: "House mode turned on"
      conditions:
        - condition: state
          entity_id: input_boolean.house_mode_away
          state: "on"

      sequence:
        - *turned_on

    - alias: "House mode turned off"
      conditions:
        - condition: state
          entity_id: input_boolean.house_mode_away
          state: "off"

      sequence:
        - *turned_off
