---
id: "maddy-leaving-work-mode"
alias: "House: Maddy Presence During Work"
description: >-
  What: Controls desk lamp based on Maddy's presence.
  When: Triggered when input_boolean.maddy_home changes during work mode.
  Why: Saves energy by turning off desk lamp when Maddy leaves, and automatically restores dining room work scene when returning.
mode: queued
trace:
  stored_traces: 25

triggers:
  - id: leaving
    platform: state
    entity_id:
      - input_boolean.maddy_home
    to: "off"

  - id: arriving
    platform: state
    entity_id:
      - input_boolean.maddy_home
    to: "on"

conditions:
  - condition: state
    entity_id: input_select.house_mode
    state: "work"

action:
  - choose:
      - alias: "Maddy leaving - turn off desk lamp"
        conditions:
          - condition: trigger
            id: leaving
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.maddys_desk_lamp_light

      - alias: "Maddy arriving - turn on desk lamp"
        conditions:
          - condition: trigger
            id: arriving
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.dining_room_work
            data:
              transition: 2.5
