---
id: "5a3d6a60-86ab-408b-b6db-c5a053281a34"
alias: "House: Mode Control"
description: >-
  What: Controls the house mode state (input_select.house_mode) using a priority-based system.
  When: Triggered by time patterns, away mode boolean changes, end-of-day signal, and system events.
  Why: Provides automated mode transitions based on time-of-day while protecting critical modes (away, sleep, bedtime) from inappropriate overrides.
  See automations/house/README.md for full documentation.
mode: queued
trace:
  stored_traces: 25

triggers:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  # Every hour
  - platform: time_pattern
    hours: /1
    minutes: 0

  # Every 30 minute
  - platform: time_pattern
    minutes: /30

  - id: end_of_day_signal
    platform: state
    entity_id:
      - input_boolean.end_of_day_signal
    to: "on"

  - id: house_away_turned_on
    platform: state
    entity_id:
      - input_boolean.house_mode_away
    to: "on"

  - id: house_away_turned_off
    platform: state
    entity_id:
      - input_boolean.house_mode_away
    to: "off"

  - platform: state
    entity_id:
      - input_boolean.holidays
    to: ~

variables:
  anchors:
    - &turn_on_away_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "away"

    - &turn_on_bedtime_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "bedtime"

    - &turn_on_work_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "work"

    - &turn_on_wakeup_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "wake up"

    - &wake_up_time_conditions
      or:
        - alias: "Wake-up time Weekdays"
          condition: time
          after: "{{ states('input_datetime.wake_up_weekday_start') }}"
          before: "{{ states('input_datetime.wake_up_weekday_end') }}"
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - alias: "Wake-up time Weekends"
          condition: time
          after: "{{ states('input_datetime.wake_up_weekend_start') }}"
          before: "{{ states('input_datetime.wake_up_weekend_end') }}"
          weekday:
            - sat
            - sun

    - &turn_on_relaxation_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "relaxation"

    - &turn_on_dinner_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "dinner"

    - &turn_on_sleep_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "sleep"

    - &turn_on_default_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "default"

action:
  - choose:
      # ============================================
      # PRIORITY 1: EVENT-DRIVEN MODE CHANGES
      # These take precedence over time-based scheduling
      # ============================================

      - alias: "Away mode turned ON"
        conditions:
          - condition: trigger
            id: house_away_turned_on
        sequence:
          <<: *turn_on_away_mode

      # ============================================
      # PRIORITY 2: PROTECTED MODES
      # Prevent time-based triggers from overriding certain modes
      # ============================================

      # Away mode is ALWAYS protected unless explicitly turned off via house_away_turned_off
      # This prevents ANY time-based triggers (including wake-up time) from overriding away mode
      - alias: "Do nothing when in away mode unless explicitly returning home"
        conditions:
          and:
            - alias: "Not caused by returning home"
              condition: template
              value_template: "{{ trigger.id != 'house_away_turned_off' }}"
            - alias: "House mode is away"
              condition: state
              entity_id: input_select.house_mode
              state: "away"
        sequence: []

      # Bedtime and sleep modes are protected unless it's wake-up time or returning home
      # This allows wake-up time to transition from bedtime/sleep but NOT from away
      - alias: "Do nothing (bedtime/sleep modes) unless returning home or waking up"
        conditions:
          and:
            - alias: "Not caused by returning home"
              condition: template
              value_template: "{{ trigger.id != 'house_away_turned_off' }}"
            - alias: "Not wake up time"
              not:
                - <<: *wake_up_time_conditions
            - or:
                - alias: "House mode bedtime on"
                  condition: state
                  entity_id: input_select.house_mode
                  state: "bedtime"
                - alias: "House mode sleep on"
                  condition: state
                  entity_id: input_select.house_mode
                  state: "sleep"
        sequence: []

      # Bedtime mode turned on when end-of-day signal received
      - alias: "Turn on Bedtime house mode"
        conditions:
          - alias: "Within bedtime window"
            condition: time
            after: "{{ states('input_datetime.bedtime_window_start') }}"
            before: "{{ states('input_datetime.bedtime_window_end') }}"
          - alias: "End of day signal received"
            condition: trigger
            id: end_of_day_signal
        sequence:
          <<: *turn_on_bedtime_mode

      # Transition from bedtime to sleep mode
      - alias: "Bedtime to Sleep transition"
        conditions:
          - alias: "Currently in bedtime mode"
            condition: state
            entity_id: input_select.house_mode
            state: "bedtime"
          - alias: "Sleep time reached"
            condition: time
            after: "{{ states('input_datetime.sleep_time_start') }}"
            before: "{{ states('input_datetime.sleep_time_end') }}"
        sequence:
          <<: *turn_on_sleep_mode

      # ============================================
      # PRIORITY 3: TIME-BASED MODE SCHEDULING
      # These run on time patterns and respect protected modes
      # ============================================

      - alias: "Relaxation mode handling"
        conditions:
          - or:
              - alias: "Relaxation time"
                condition: time
                after: "{{ states('input_datetime.relaxation_time') }}"
              - alias: "Time between midnight and sleep start"
                condition: time
                after: "00:00:00"
                before: "{{ states('input_datetime.sleep_time_start') }}"
        sequence:
          <<: *turn_on_relaxation_mode

      - alias: "Dinner mode handling"
        conditions:
          - alias: "Dinner time"
            condition: time
            after: "{{ states('input_datetime.dinner_time') }}"
        sequence:
          <<: *turn_on_dinner_mode

      - alias: "Default mode handling"
        conditions:
          - alias: "Default hours Weekends"
            condition: time
            after: "{{ states('input_datetime.default_weekend_start') }}"
            before: "{{ states('input_datetime.default_weekend_end') }}"
            weekday:
              - sat
              - sun
        sequence:
          <<: *turn_on_default_mode

      - alias: "Work mode handling"
        conditions:
          - alias: "Not on Holidays"
            condition: state
            entity_id: input_boolean.holidays
            state: "off"
          - alias: "Work hours Weekdays"
            condition: time
            after: "{{ states('input_datetime.work_start') }}"
            before: "{{ states('input_datetime.work_end') }}"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          <<: *turn_on_work_mode

      - alias: "Wake-up mode handling"
        conditions:
          <<: *wake_up_time_conditions
        sequence:
          <<: *turn_on_wakeup_mode

      # Always sleep mode during sleep hours
      - alias: "Sleep mode handling"
        conditions:
          - alias: "Sleep time window"
            condition: time
            after: "{{ states('input_datetime.sleep_time_start') }}"
            before: "{{ states('input_datetime.sleep_time_end') }}"
        sequence:
          <<: *turn_on_sleep_mode

    default:
      <<: *turn_on_default_mode
