---
id: "5a3d6a60-86ab-408b-b6db-c5a053281a34"
alias: "House: Mode Control"
description: >-
  This is used to control the `input_select` for the state of the house, it can then be used by other automations to make decisions against.
mode: queued
trace:
  stored_traces: 25

triggers:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  # Every hour
  - platform: time_pattern
    hours: /1
    minutes: 0

  # Every 30 minute
  - platform: time_pattern
    minutes: /30

  - id: apple_tv_off
    platform: state
    entity_id:
      - media_player.lounge_room
    to: "off"

  - id: house_away_turned_on
    platform: state
    entity_id:
      - input_boolean.house_mode_away
    to: "on"

  - id: house_away_turned_off
    platform: state
    entity_id:
      - input_boolean.house_mode_away
    to: "off"

  - platform: state
    entity_id:
      - input_boolean.holidays
    to: ~

variables:
  anchors:
    - &turn_on_away_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "away"

    - &turn_on_bedtime_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "bedtime"

    - &turn_on_work_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "work"

    - &turn_on_wakeup_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "wake up"

    - &wake_up_time_conditions
      or:
        - alias: "Time 0600 -> 0800 Weekdays"
          condition: time
          after: "06:00:00"
          before: "08:00:00"
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - alias: "Time 0700 -> 0900 Weekends"
          condition: time
          after: "07:00:00"
          before: "09:00:00"
          weekday:
            - sat
            - sun

    - &protected_modes
      or:
        - alias: "House mode Away already on"
          condition: state
          entity_id: input_select.house_mode
          state: "away"
        - alias: "House mode bedtime on"
          condition: state
          entity_id: input_select.house_mode
          state: "bedtime"
        - alias: "House mode sleep on"
          condition: state
          entity_id: input_select.house_mode
          state: "sleep"

    - &turn_on_relaxation_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "relaxation"

    - &turn_on_dinner_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "dinner"

    - &turn_on_sleep_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "sleep"

    - &turn_on_default_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "default"

action:
  - choose:
      # ============================================
      # PRIORITY 1: EVENT-DRIVEN MODE CHANGES
      # These take precedence over time-based scheduling
      # ============================================

      - alias: "Away mode turned ON"
        conditions:
          - condition: trigger
            id: house_away_turned_on
        sequence:
          <<: *turn_on_away_mode

      # ============================================
      # PRIORITY 2: PROTECTED MODES
      # Prevent time-based triggers from overriding certain modes
      # ============================================

      # Away mode is ALWAYS protected unless explicitly turned off via house_away_turned_off
      # This prevents ANY time-based triggers (including wake-up time) from overriding away mode
      - alias: "Do nothing when in away mode unless explicitly returning home"
        conditions:
          and:
            - alias: "Not caused by returning home"
              condition: template
              value_template: "{{ trigger.id != 'house_away_turned_off' }}"
            - alias: "House mode is away"
              condition: state
              entity_id: input_select.house_mode
              state: "away"
        sequence: []

      # Bedtime and sleep modes are protected unless it's wake-up time or returning home
      # This allows wake-up time to transition from bedtime/sleep but NOT from away
      - alias: "Do nothing (bedtime/sleep modes) unless returning home or waking up"
        conditions:
          and:
            - alias: "Not caused by returning home"
              condition: template
              value_template: "{{ trigger.id != 'house_away_turned_off' }}"
            - alias: "Not wake up time"
              not:
                - <<: *wake_up_time_conditions
            - or:
                - alias: "House mode bedtime on"
                  condition: state
                  entity_id: input_select.house_mode
                  state: "bedtime"
                - alias: "House mode sleep on"
                  condition: state
                  entity_id: input_select.house_mode
                  state: "sleep"
        sequence: []

      # Bedtime mode turned on when apple TV turned off at night
      - alias: "Turn on Bedtime house mode"
        conditions:
          - alias: "Time 2100 -> 0300"
            condition: time
            after: "21:00:00"
            before: "00:00:00"
          - alias: "Apple TV turned off"
            condition: trigger
            id: apple_tv_off
        sequence:
          <<: *turn_on_bedtime_mode

      # Transition from bedtime to sleep mode after 02:00
      - alias: "Bedtime to Sleep transition"
        conditions:
          - alias: "Currently in bedtime mode"
            condition: state
            entity_id: input_select.house_mode
            state: "bedtime"
          - alias: "Time after 0200"
            condition: time
            after: "02:00:00"
            before: "07:00:00"
        sequence:
          <<: *turn_on_sleep_mode

      # ============================================
      # PRIORITY 3: TIME-BASED MODE SCHEDULING
      # These run on time patterns and respect protected modes
      # ============================================

      - alias: "Relaxation mode handling"
        conditions:
          - or:
              - alias: "Time after 2000"
                condition: time
                after: "20:00:00"
              - alias: "Time between 0000 -> 0200"
                condition: time
                after: "00:00:00"
                before: "02:00:00"
        sequence:
          <<: *turn_on_relaxation_mode

      - alias: "Dinner mode handling"
        conditions:
          - alias: "Time after 1800"
            condition: time
            after: "18:00:00"
        sequence:
          <<: *turn_on_dinner_mode

      - alias: "Default mode handling"
        conditions:
          - alias: "Time 0900 -> 1800 Weekends"
            condition: time
            after: "09:00:00"
            before: "18:00:00"
            weekday:
              - sat
              - sun
        sequence:
          <<: *turn_on_default_mode

      - alias: "Work mode handling"
        conditions:
          - alias: "Not on Holidays"
            condition: state
            entity_id: input_boolean.holidays
            state: "off"
          - alias: "Time 0800 -> 1700 Weekdays"
            condition: time
            after: "08:00:00"
            before: "17:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          <<: *turn_on_work_mode

      - alias: "Wake-up mode handling"
        conditions:
          <<: *wake_up_time_conditions
        sequence:
          <<: *turn_on_wakeup_mode

      # Always sleep mode after 2AM before 7AM
      - alias: "Sleep mode handling"
        conditions:
          - alias: "Time after 0200 if it reaches this point"
            condition: time
            after: "02:00:00"
            before: "07:00:00"
        sequence:
          <<: *turn_on_sleep_mode

    default:
      <<: *turn_on_default_mode
