id: "5a3d6a60-86ab-408b-b6db-c5a053281a34"
alias: "House: Mode Control"
description: >-
  This is used to control the `input_boolean`'s for the state of the house, those can then be used by other automations to make decisions against.
mode: queued
trace:
  stored_traces: 25

triggers:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  - id: apple_tv_off
    platform: state
    entity_id:
      - media_player.lounge_room
    to: "off"

  - id: house_away_turned_off
    platform: state
    entity_id:
      - input_boolean.house_mode_away
    to: "off"

variables:
  anchors:
    - &turn_on_bedtime_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "bedtime"

    - &turn_on_default_mode
      service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "default"

action:
  - choose:
      # This just means if the house is already in away do not change it.
      - alias: "Do nothing"
        conditions:
          - alias: "House mode Away already on"
            condition: state
            entity_id: input_boolean.house_mode_away
            state: "on"
        sequence: []
      - alias: "Turn on Bedtime house mode"
        conditions:
          - alias: "Time 2130 -> 0300"
            condition: time
            after: "21:30:00"
            before: "03:00:00"
        sequence:
          - choose:
              - conditions:
                or:
                  - alias: "Apple TV turned off"
                    condition: trigger
                    id: apple_tv_off
                  - alias: "House Away turned off"
                    condition: trigger
                    id: house_away_turned_off
                sequence:
                  <<: *turn_on_bedtime_mode
      - alias: "Turn on Default house mode"
        conditions:
          - alias: "Time 0900 -> 2130"
            condition: time
            after: "09:00:00"
            before: "21:30:00"
        sequence:
          <<: *turn_on_default_mode
        # conditions:
        #   - alias: "Apple TV Turned off"
        #     condition: trigger
        #     id: apple_tv_off
        #   - alias: "Time 2130 -> 0300"
        #     condition: time
        #     after: "21:30:00"
        #     before: "03:00:00"
        # sequence:
        #   <<: *turn_on_bedtime_mode
