id: '5a3d6a60-86ab-408b-b6db-c5a053281a34'
alias: "House: Mode Control"
description: >-
  This is used to control the `input_boolean`'s for the state of the house, those can then be used by other automations to make decisions against.
mode: queued
trace:
  stored_traces: 25

triggers:
  - platform: homeassistant
    event: start

  - platform: event
    event_type:
      - automation_reloaded

  - id: apple_tv_off
    platform: state
    entity_id:
      - media_player.lounge_room
    to: "off"

variables:
  anchors:
    - &turn_off_all_besides_bedtime
      - alias: "Turn off Other modes"
        service: input_boolean.turn_off
        target:
          entity_id: 
            - input_boolean.house_mode_away
            - input_boolean.house_mode_sleep

    - &turn_on_bedtime_mode
      - alias: "Turn on Bedtime mode"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.house_mode_bedtime

action:
  - choose:
    - alias: "Do nothing"
      conditions:
        - alias: "House mode Away already on"
          condition: state
          entity_id: input_boolean.house_mode_away
          state: "on"
      sequence: []
    - alias: "Turn on Bedtime house mode"
      conditions:
        - alias: "Apple TV Turned off"
          condition: trigger
          id: apple_tv_off
        - alias: "Time 2130 -> 0300"
          condition: time
          after: "21:30:00"
          before: "03:00:00"
      sequence:
        <<:
          - *turn_off_all_besides_bedtime
          - *turn_on_bedtime_mode
