id: "2a11b66c-5342-40cb-b7fc-ad90d9873673"
alias: "House: Sleep"
description: >-
mode: queued
trace:
  stored_traces: 25

triggers:
  - id: to
    platform: state
    entity_id:
      - input_select.house_mode
    to: sleep

variables:
  anchors:
    - &to_action
      - alias: "Turn on All Sleep scenes"
        service: script.turn_on
        target:
          entity_id: script.sleep_scenes

action:
  - choose:
      - alias: "House mode changed to sleep"
        conditions:
          - condition: trigger
            id: to
        sequence:
          <<: *to_action
