---
id: "019395ae-d0c0-40b8-9d67-c72dcf108126"
alias: "House: Work"
description: >-
mode: queued
trace:
  stored_traces: 25

triggers:
  - id: to
    platform: state
    entity_id:
      - input_select.house_mode
    to: work

variables:
  anchors:
    - &to_action
      - alias: "Turn on All Sleep scenes"
        service: script.turn_on
        target:
          entity_id: script.work_scenes

action:
  - choose:
      - alias: "House mode changed to work"
        conditions:
          - condition: trigger
            id: to
        sequence:
          <<: *to_action
